name: ROS1 CI Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  build-ros1:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-bionic-ros-melodic-ros-base-latest
    steps:
      - name: Fix Bugs in ros-tooling/action-ros-ci
        run: sudo chown -R rosbuild:rosbuild "$HOME" .
      - name: Build Package
        uses: ros-tooling/action-ros-ci@0.0.19
        with:
          package-name: tvm_vendor
          target-ros1-distro: melodic
          vcs-repo-file-url: ""
