name: ROS2 CI Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  build-ros2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros-version: [dashing, foxy]
        include:
          - ros-version: dashing
            image: ros:dashing
          - ros-version: foxy
            image: ros:foxy
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create Workspace
        run: |
          mkdir -p src_tmp/tvm_vendor
          mv `find -maxdepth 1 -not -name . -not -name src_tmp` src_tmp/tvm_vendor/
          mv src_tmp/ src/
      - name: Install Dependencies
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          apt-get update && rosdep update; \
          rosdep install --from-paths src --ignore-src -y'
      - name: Build Workspace
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          colcon build'
      - name: Run Tests
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          colcon test; \
          colcon test-result --verbose'
